import Head from "next/head";
import {
  VStack,
  Center,
  Text,
  Heading,
  AbsoluteCenter,
  Button,
  Input,
  FormControl,
  Select,
} from "@chakra-ui/react";
import { TypeAnimation } from "react-type-animation";

export default function Home() {
  return (
    <>
      <Head>
        <title>RoadmapAi</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center>
        <VStack maxW="6xl" h="100vh" gap="50px">
          <Heading>Create your personal roadmap</Heading>
          <FormControl id="promt" fontSize={"2xl"} pt="10">
            <Text>What space is your roadmap for?</Text>
            <Select
              placeholder="Tech"
              _placeholder={{ color: "gray.500" }}
              textAlign="match-parent"
              width={"50"}
              //   onChange={handleDropDownChange}
            >
              <option>AI</option>
              <option>Engineering</option>
              <option>Wellness</option>
              <option>Exercise</option>
              <option>Religion</option>
            </Select>
            <Text>I want a roadmap to</Text>
            <Input placeholder="specific thing" size="lg" />
          </FormControl>
          <Button bg="#4FAD27" color="white" size="lg">
            {" "}
            Create a Roadmap
          </Button>
        </VStack>
      </Center>
    </>
  );
}
